### ISSUE TITLE
如何在linux上建立开发环境？

### ISSUE THREAD

**Issue by BackMountainDevil** [YaoZeyuan/zhihuhelp#104]
```bash
git clone ...
cd zhihuhelp
npm install # 错误1
npm run ace Init:Env # 错误2 缺少 ace 模块
```
## 错误1
```
0 verbose cli /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.15.1
2 info using node@v18.7.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/kearney/Documents/code/zhihuhelp/.npmrc Completed in 2ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/home/kearney/.npmrc Completed in 1ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 3ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 20ms
19 timing npm:load:configload Completed in 20ms
20 timing npm:load:mkdirpcache Completed in 5ms
21 timing npm:load:mkdirplogs Completed in 1ms
22 verbose title npm rebuild sharp@0.29.1 sqlite3@5.0.2
23 verbose argv "rebuild" "sharp@0.29.1" "sqlite3@5.0.2"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 4ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/kearney/.npm/_logs
28 verbose logfile /home/kearney/.npm/_logs/2022-08-06T07_19_27_176Z-debug-0.log
29 timing npm:load:logFile Completed in 7ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 42ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms
36 timing build:queue Completed in 4ms
37 info run sharp@0.29.1 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
38 info run sqlite3@5.0.2 install node_modules/sqlite3 node-pre-gyp install --fallback-to-build
39 info run sqlite3@5.0.2 install { code: 1, signal: null }
40 timing command:rebuild Completed in 2603ms
41 verbose stack Error: command failed
41 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
41 verbose stack     at ChildProcess.emit (node:events:513:28)
41 verbose stack     at maybeClose (node:internal/child_process:1091:16)
41 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
42 verbose pkgid sqlite3@5.0.2
43 verbose cwd /home/kearney/Documents/code/zhihuhelp
44 verbose Linux 5.15.57-2-MANJARO
45 verbose node v18.7.0
46 verbose npm  v8.15.1
47 error code 1
48 error path /home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3
49 error command failed
50 error command sh /tmp/install-ae854f85.sh
51 error Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --msvs_version=2015' (1)
52 error node-pre-gyp info it worked if it ends with ok
52 error node-pre-gyp info using node-pre-gyp@0.11.0
52 error node-pre-gyp info using node@18.7.0 | linux | x64
52 error node-pre-gyp WARN Using request for node-pre-gyp https download 
52 error node-pre-gyp info build requesting source compile
52 error gyp info it worked if it ends with ok
52 error gyp info using node-gyp@9.1.0
52 error gyp info using node@18.7.0 | linux | x64
52 error gyp info ok 
52 error gyp info it worked if it ends with ok
52 error gyp info using node-gyp@9.1.0
52 error gyp info using node@18.7.0 | linux | x64
52 error gyp info find Python using Python version 3.10.5 found at "/usr/bin/python3"
52 error gyp info spawn /usr/bin/python3
52 error gyp info spawn args [
52 error gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
52 error gyp info spawn args   'binding.gyp',
52 error gyp info spawn args   '-f',
52 error gyp info spawn args   'make',
52 error gyp info spawn args   '-I',
52 error gyp info spawn args   '/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/build/config.gypi',
52 error gyp info spawn args   '-I',
52 error gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
52 error gyp info spawn args   '-I',
52 error gyp info spawn args   '/home/kearney/.electron-gyp/14.0.0/include/node/common.gypi',
52 error gyp info spawn args   '-Dlibrary=shared_library',
52 error gyp info spawn args   '-Dvisibility=default',
52 error gyp info spawn args   '-Dnode_root_dir=/home/kearney/.electron-gyp/14.0.0',
52 error gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
52 error gyp info spawn args   '-Dnode_lib_file=/home/kearney/.electron-gyp/14.0.0/<(target_arch)/node.lib',
52 error gyp info spawn args   '-Dmodule_root_dir=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3',
52 error gyp info spawn args   '-Dnode_engine=v8',
52 error gyp info spawn args   '--depth=.',
52 error gyp info spawn args   '--no-parallel',
52 error gyp info spawn args   '--generator-output',
52 error gyp info spawn args   'build',
52 error gyp info spawn args   '-Goutput_dir=.'
52 error gyp info spawn args ]
52 error gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
52 error gyp ERR! configure error 
52 error gyp ERR! stack Error: `gyp` failed with exit code: 1
52 error gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:284:16)
52 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
52 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
52 error gyp ERR! System Linux 5.15.57-2-MANJARO
52 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--msvs_version=2015"
52 error gyp ERR! cwd /home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3
52 error gyp ERR! node -v v18.7.0
52 error gyp ERR! node-gyp -v v9.1.0
52 error gyp ERR! not ok 
52 error node-pre-gyp ERR! build error 
52 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --msvs_version=2015' (1)
52 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/kearney/Documents/code/zhihuhelp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
52 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
52 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
52 error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
52 error node-pre-gyp ERR! System Linux 5.15.57-2-MANJARO
52 error node-pre-gyp ERR! command "/usr/bin/node" "/home/kearney/Documents/code/zhihuhelp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
52 error node-pre-gyp ERR! cwd /home/kearney/Documents/code/zhihuhelp/node_modules/sqlite3
52 error node-pre-gyp ERR! node -v v18.7.0
52 error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
52 error node-pre-gyp ERR! not ok
53 verbose exit 1
54 timing npm Completed in 2729ms
55 verbose unfinished npm timer build 1659770368673
56 verbose unfinished npm timer build:deps 1659770368674
57 verbose unfinished npm timer build:run:install 1659770368678
58 verbose unfinished npm timer build:run:install:node_modules/sharp 1659770368678
59 verbose unfinished npm timer build:run:install:node_modules/sqlite3 1659770368692
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /home/kearney/.npm/_logs/2022-08-06T07_19_27_176Z-debug-0.log

```

**Comment by YaoZeyuan** [comment]
可以基于3.0.0试下
