### ISSUE TITLE
无法导出 @听月上官 用户的回答记录

### ISSUE THREAD

**Issue by YaoZeyuan** [YaoZeyuan/zhihuhelp#31]
导出回答的用户名称：听月上官

回答链接：https://www.zhihu.com/people/ting-yue-shang-guan-32/answers

相关日志 =>

> 
> 2019-10-11 14:11:37.766: [GenerateAuthor] 获取回答列表
> 
> 2019-10-11 14:11:37.840: [GenerateAuthor] 回答列表获取完毕, 共0条答案
> 
> 2019-10-11 14:11:37.842: [GenerateAuthor] catch error
> 
> 2019-10-11 14:11:37.844: [GenerateAuthor] TypeError: Cannot read property 'question' of undefined
> 
> at Function.generateSingleItemElement (D:\software\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:29:73)
> 
> at Function.renderInSinglePage (D:\software\知乎助手\zhihuhelp\resources\app\dist\view\answer.js:54:34)
> 
> at D:\software\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:94:38
> 
> at Generator.next (<anonymous>)
> 
> at asyncGeneratorStep (D:\software\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:24:103)
> 
> at _next (D:\software\知乎助手\zhihuhelp\resources\app\dist\command\generate\author.js:26:194)
> 
> 2019-10-11 14:11:37.846: [GenerateAuthor] command finish

**Comment by ProfessorX** [comment]
感觉是知乎官方对爬虫做了限制。

我的log里面看得到爬着爬着验证码就跳出来了。

**Comment by YaoZeyuan** [comment]
> 感觉是知乎官方对爬虫做了限制。
> 
> 我的log里面看得到爬着爬着验证码就跳出来了。

是的, 代码里没加频次限制, 爬的太快了~

**Comment by ProfessorX** [comment]
> 个人方案：
> 使用clumsy模拟20%丢包减少爬虫的并发量（约每秒抓取15个回答），减缓zhihu服务器压力避免被封
> http://jagt.github.io/clumsy/cn/index.html
> 建议作者在新版本中添加 并发限制 的功能

老哥你咋配置的能说下不。

我直接配outbound 丢包20% 感觉不起作用啊。

还是抓不了数据。

有个用户1000多个回答呢，要不你那边帮忙抓一下。

https://www.zhihu.com/people/songyun911/answers

**Comment by popy32** [comment]
> > 个人方案：
> > 使用clumsy模拟20%丢包减少爬虫的并发量（约每秒抓取15个回答），减缓zhihu服务器压力避免被封
> > http://jagt.github.io/clumsy/cn/index.html
> > 建议作者在新版本中添加 并发限制 的功能
> 
> 老哥你咋配置的能说下不。
> 
> 我直接配outbound 丢包20% 感觉不起作用啊。
> 
> 还是抓不了数据。
> 
> 有个用户1000多个回答呢，要不你那边帮忙抓一下。
> 
> https://www.zhihu.com/people/songyun911/answers

Preset: all sending packets
Function: Drop  Inbound OutBount Chance: 15%
