### ISSUE TITLE
更新后不能用

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp#46]
异常原因:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

基本不能用，都是这问题

**Comment by YaoZeyuan** [comment]
ok，我明天改下。
另外这个应该跟Python版本也有关系，我用最新版的Python2.7.10就没报这个错误

**Comment by YaoZeyuan** [comment]
现在的解析速度也挺慢的其实，已经找到性能瓶颈了，我明天晚上优化下

**Comment by shuijinliuxi** [comment]
我用的是Python 2.7.11

**Comment by YaoZeyuan** [comment]
翻译过来是这个"/Users/xxx/Desktop/zhihuhelp1.7.3.5./知乎助手生成的电子书/作者_袁浩瀚(id47).epub"
1.7.3.5后边多了个点『.』
我更新了一般，你试试新版行不

**Comment by shuijinliuxi** [comment]
试了下新版，还是多了个点『.』，然后我把文件目录加了个点『.』，就显示两个点『.』：
IOError: [Errno 2] No such file or directory: u'/Users/xxx/Desktop/zhihuhelp1.7.3.6../\u77e5\u4e4e\u52a9\u624b\u751f\u6210\u7684\u7535\u5b50\u4e66/\u4f5c\u8005_\u8881\u6d69\u701a(id47).epub'

**Comment by YaoZeyuan** [comment]
嗯，这是代码的问题，我在Path.py这个文件里多了一个『.』
去掉了已经。
另外你用的是什么操作系统，为什么之前我在Windows上没测出来？

**Comment by YaoZeyuan** [comment]
又更新了一版，再试下吧：）

**Comment by shuijinliuxi** [comment]
2016-01-04 21:49:56,455 - main.py:71 - main - 开始自数据库中生成电子书数据
Traceback (most recent call last):
  File "zhihuHelp.py", line 11, in <module>
    helper.start()
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/main.py", line 54, in start
    self.create_book(line, counter)  # 一行内容代表一本电子书
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/main.py", line 72, in create_book
    book = Book(task_package.book_list)
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/book.py", line 21, in __init__
    raw_book_list = [book.catch_data() for book in self.flatten(raw_sql_book_list)]
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/container/initialbook.py", line 48, in catch_data
    self.catch_info()
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/container/initialbook.py", line 62, in catch_info
    info = DB.wrap(Type.info_table[self.kind], info)
  File "/Users/xxx/Desktop/zhihuhelp1.7.3.7/src/tools/db.py", line 76, in wrap
    return {k: v for (k, v) in zip(template[kind], result)}
TypeError: zip argument #2 must support iteration

**Comment by YaoZeyuan** [comment]
很诡异啊。
你是什么操作系统？另外，把原先的代码包全删掉，直接解压一个新的出来能用吗？

**Comment by YaoZeyuan** [comment]
另外，发下ReadList的内容，我测试一下

**Comment by shuijinliuxi** [comment]
不好意思，最近太忙了，没时间看。
我重新下载了，重新测试没那个问题了。
不过发现有其他问题：

1、链接的处理似乎有些问题：
开始下载图片http:https://zhihu.com/equation?tex=%2B%5Cbeta_5%5Ctimes2016-01-18 13:06:27,173 - http.py:55 - main - 异常原因:no host given
2016-01-18 13:06:27,173 - http.py:55 - main - 异常原因:no host given
2016-01-18 13:06:27,173 - http.py:55 - main - 异常原因:no host given
2016-01-18 13:06:27,173 - http.py:53 - main - 网络连接异常
2016-01-18 13:06:27,173 - http.py:54 - main - 异常页面:http:https://zhihu.com/equation?tex=U%3D%5Calpha+lnx%2B%5Cbeta+lny
开始下载图片http:https://zhihu.com/equation?tex=%5Chat%7B%5Cbeta%7D2016-01-18 13:06:27,173 - http.py:55 - main - 异常原因:no host given

2、文件问题：
  File "zhihuHelp.py", line 11, in <module>
    helper.start()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 54, in start
    self.create_book(line, counter)  # 一行内容代表一本电子书
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 73, in create_book
    book.create()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/book.py", line 171, in create
    self.create_book(book_package)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/book.py", line 118, in create_book
    epub = Epub(title)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/epub.py", line 25, in __init__
    self.init_path()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/epub.py", line 44, in init_path
    EpubPath.init_epub_path(Path.get_pwd())
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/tools/epub_path.py", line 44, in init_epub_path
    Path.chdir(EpubPath.oebps_path)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/zhihuhelp_tools/path.py", line 57, in chdir
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '/Users/oyc/Desktop/zhihuhelp1.7.3.711/\xe9\x90\xad\xe3\x83\xa4\xe7\xae\xae\xe9\x90\xa2\xe9\x9d\x9b\xe7\x93\x99\xe6\xb6\x94\xef\xb8\xbf\xe5\xa4\x8d\xe9\x8f\x83\xe6\x83\xb0\xe7\xa5\xab\xe5\xa9\xa7\xe6\x84\xac\xe7\xb0\xb1/\xe6\xb6\x93\xe6\x92\xb4\xe7\x88\xae_\xe6\xa5\xb8\xe5\xa5\xb8\xe5\xa5\x94\xe6\xa5\xb8\xe9\x97\xb4\xe7\xac\x81\xe9\x8f\x89\xef\xbf\xa0\xe5\xa5\x94(seasee)/OEBPS'

以下是我使用有问题的链接：
http://zhuanlan.zhihu.com/zhimovie
http://zhuanlan.zhihu.com/AndyLee
http://zhuanlan.zhihu.com/daozhui
http://zhuanlan.zhihu.com/chenqin

**Comment by YaoZeyuan** [comment]
ok，我晚上回家改下：）
