### ISSUE TITLE
最新版抓取内容失败

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp#58]
2016-02-16 18:47:07,732 - http.py:48 - main - 网页打开失败
2016-02-16 18:47:07,732 - http.py:49 - main - 失败页面:https://www.zhihu.com/people/frank-hu-56/answers?order_by=vote_num&page=16
2016-02-16 18:47:07,733 - http.py:50 - main - 失败代码:429
2016-02-16 18:47:07,733 - http.py:51 - main - 失败原因:
2016-02-16 18:47:07,737 - worker.py:107 - main - 开始抓取https://www.zhihu.com/people/frank-hu-56/answers?order_by=vote_num&page=19的内容
2016-02-16 18:47:07,738 - http.py:48 - main - 网页打开失败
2016-02-16 18:47:07,739 - http.py:48 - main - 网页打开失败
2016-02-16 18:47:07,740 - http.py:49 - main - 失败页面:https://www.zhihu.com/people/frank-hu-56/answers?order_by=vote_num&page=17
2016-02-16 18:47:07,754 - http.py:49 - main - 失败页面:https://www.zhihu.com/people/frank-hu-56/answers?order_by=vote_num&page=18

Traceback (most recent call last):
  File "zhihuHelp.py", line 11, in <module>
    helper.start()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 54, in start
    self.create_book(line, counter)  # 一行内容代表一本电子书
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 72, in create_book
    book = Book(task_package.book_list)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/book.py", line 21, in **init**
    raw_book_list = [book.catch_data() for book in self.flatten(raw_sql_book_list)]
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/container/initialbook.py", line 48, in catch_data
    self.catch_info()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/container/initialbook.py", line 62, in catch_info
    info = DB.wrap(Type.info_table[self.kind], info)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/tools/db.py", line 76, in wrap
    return {k: v for (k, v) in zip(template[kind], result)}
TypeError: zip argument #2 must support iteration

**Comment by knarfeh** [comment]
这个应该是因为线程数设置太多了？多运行一两次应该可以生成电子书的。

**Comment by shuijinliuxi** [comment]
重新运行了一下，又出现其他问题：

Traceback (most recent call last):
  File "zhihuHelp.py", line 11, in <module>
    helper.start()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 54, in start
    self.create_book(line, counter)  # 一行内容代表一本电子书
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/main.py", line 73, in create_book
    book.create()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/book.py", line 171, in create
    self.create_book(book_package)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/book.py", line 118, in create_book
    epub = Epub(title)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/epub.py", line 25, in __init__
    self.init_path()
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/epub.py", line 44, in init_path
    EpubPath.init_epub_path(Path.get_pwd())
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/tools/epub_path.py", line 44, in init_epub_path
    Path.chdir(EpubPath.oebps_path)
  File "/Users/oyc/Desktop/zhihuhelp1.7.3.711/src/lib/epub/zhihuhelp_tools/path.py", line 57, in chdir
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '/Users/oyc/Desktop/zhihuhelp1.7.3.711/\xe9\x90\xad\xe3\x83\xa4\xe7\xae\xae\xe9\x90\xa2\xe9\x9d\x9b\xe7\x93\x99\xe6\xb6\x94\xef\xb8\xbf\xe5\xa4\x8d\xe9\x8f\x83\xe6\x83\xb0\xe7\xa5\xab\xe5\xa9\xa7\xe6\x84\xac\xe7\xb0\xb1/\xe6\xb6\x93\xe6\x92\xb4\xe7\x88\xae_\xe6\xa5\xb8\xe5\xa5\xb8\xe5\xa5\x94\xe6\xa5\xb8\xe9\x97\xb4\xe7\xac\x81\xe9\x8f\x89\xef\xbf\xa0\xe5\xa5\x94(seasee)/OEBPS'

**Comment by YaoZeyuan** [comment]
ok，我去看一下

**Comment by YaoZeyuan** [comment]
现在已经可以了:joy:
