### ISSUE TITLE
[Bug] 很多Bug，希望作者有空可以修复一下

### ISSUE THREAD

**Issue by Evyde** [YaoZeyuan/zhihuhelp#65]
# 开发环境搭建阶段
- 缺少`request-promise`包，必须手动安装
- 原README文件中，关于使用GUI运行的部分已失效。现在不需要手动编译SQLite 3（也有可能是NPM在安装的时候已经装好环境了（NPM在安装的时候有一个自动安装必要环境的选项）），并且也不需要手动更改代码了，只需要在`npm run startgui`的时候加入`--debug`选项即可，即`npm run startgui --debug`
- 原README文件中，指示使用命令行运行部分我跑不通，执行完`npm install`和`npm run ace`之后提示（当然很有可能是我操作不当）
```log
  _ace.default.addCommand(require(command)['default']);
               ^

TypeError: Cannot read property 'addCommand' of undefined
    at Object.<anonymous> (C:\Users\****\Desktop\zhihuhelp-master\dist\ace.js:34:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zhihuhelp@2.3.1 ace: `node dist/ace.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zhihuhelp@2.3.1 ace script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
# 运行阶段
- [x] API问题，这个知乎只换了动态和收藏的API，别的好像没换
- [x] 建议合并Pull Request #59 
- [ ] 在Issue #46 中，增加的判断希望可以改成等待用户输入验证码，或者用Tensorflow、PaddleOCR等识别验证码自动填写（这个验证码有且只有字母且几乎无混淆）
- [x] 在Issue #48 中，有人提及了图片的判断问题，我这里测试所有图片不管是原图还是高清都无法下载，可能是API变更导致无法获取正确地址
# Feature Request
- [ ] 希望加入当前登录用户的各种信息获取选项，用于一键备份回答等内容
- [ ] 希望可以加入自定义API地址，这样就不必作者频繁修改API地址了
- [ ] 收藏夹在生成的电子书中以章节和回答名分类
- [ ] 多个任务同时生成电子书时，EPUB电子书的层级关系希望可以做的更明显一些
- [ ] 可以允许用户自定义电子书背景或主题
# 测试环境
Windows 10 LTSC，NPM Version: 6.14.11，NodeJS Version: 14.16.0

**Comment by YaoZeyuan** [comment]
感谢, 我今天集中更新了一版, 现在应该是可以用了. 可以用新版试下

**Comment by YaoZeyuan** [comment]
今天太晚了, issue 我这两天看下

**Comment by ForeverOpp** [comment]
又发现了新的Bug，当文件名过长时，创建文件夹会失败。
具体日志：
```log
2021-11-18 14:41: [GenerateCustomer] catch error 
2021-11-18 14:41: [GenerateCustomer] ShellJSInternalError: EINVAL: invalid argument, mkdir 'C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\缓存文件\epub\大概600个字符的文件名'
    at mkdirSync (fs.js:1009:3)
    at Object.e.mkdirSync (electron/js2c/asar_bundle.js:5:12191)
    at mkdirSyncRecursive (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\node_modules\shelljs\src\mkdir.js:32:6)
    at C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\node_modules\shelljs\src\mkdir.js:81:9
    at Array.forEach (<anonymous>)
    at Object._mkdir (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\node_modules\shelljs\src\mkdir.js:59:8)
    at Object.mkdir (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\node_modules\shelljs\src\common.js:384:25)
    at GenerateCustomer.initStaticRecource (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\base.js:234:22)
    at C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:677:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:46:103)
    at _next (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:48:194)
    at C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:48:364
    at new Promise (<anonymous>)
    at C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:48:97
    at GenerateCustomer.generateEpub (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:780:7)
    at C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:656:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:46:103)
    at _next (C:\Users\Evyde\AppData\Local\Programs\zhihuhelp\resources\app\dist\command\generate\customer.js:48:194) 
```

**Comment by YaoZeyuan** [comment]
收到😂

**Comment by ForeverOpp** [comment]
> 收到😂

哈哈其实我感觉是Windows路径长度限制的问题，非要解决的话，要不就是直接禁用，但是需要管理员权限；要不就是自动生成的文件名限制字符数量就行。

谢谢作者了，我已经把我的数据备份下来了，提一些功能性的建议：
- 收藏夹在生成的电子书中以章节和回答名分类
- 多个任务同时生成电子书时，EPUB电子书的层级关系希望可以做的更明显一些
- 可以允许用户自定义电子书背景或主题

暂时就这些了。
