### ISSUE TITLE
专栏api中，一些专栏文章没有column这一属性

### ISSUE THREAD

**Issue by knarfeh** [YaoZeyuan/ZhihuHelp#71]
在爬取 http://zhuanlan.zhihu.com/FrontendMagazine 的过程中，出现KeyError: 'column':

报错信息：

```
2016-04-05 21:12:55,028 - worker.py:107 - main - 开始抓取https://zhuanlan.zhihu.com/api/columns/FrontendMagazine/posts?limit=10&offset=90的内容
正在解析第1/10张页面2016-04-05 21:12:55,677 - worker.py:129 - main - 所有内容抓取完毕，开始对页面进行解析
Traceback (most recent call last):
  File "/Users/Frank/PycharmProjects/ZhihuHelp/zhihuHelp.py", line 16, in <module>
    helper.start()
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/main.py", line 57, in start
    self.create_book(line, counter)  # 一行内容代表一本电子书
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/main.py", line 76, in create_book
    worker_factory(task_package.work_list)  # 执行抓取程序
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/worker.py", line 369, in worker_factory
    worker.start()
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/worker.py", line 75, in start
    self.start_worker()
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/worker.py", line 134, in start_worker
    self.parse_content(content)
  File "/Users/Frank/PycharmProjects/ZhihuHelp/src/worker.py", line 345, in parse_content
    article['column_id'] = info['column']['slug']
KeyError: 'column'
```

**Comment by YaoZeyuan** [comment]
今天第一天正点下班，原先打算今天发一版的，但想了想，还是先把zhihu2json做完好了，反正周末不加班，可以慢慢干：）
